[server]
headless = true
runOnSave = false

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#cc0000"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f7f7f7"
textColor = "#1a1a1a"
font = "sans serif"
